import React, { useEffect, useState } from "react";
import { useOutletContext } from "react-router-dom";
import { TrendingUp, Users,  Calendar, RefreshCw, FileText, CheckCircle,IndianRupee } from "lucide-react";
import api from "../../Services/mainApi";
import toast from "react-hot-toast";

interface Appointment {
  _id: string;
  doctorName: string;
  patientName: string;
  fees: number;
  date: string;
  paymentMethod: string;
  transactionId: string;
  type: string;
}

interface DoctorRevenue {
  doctorName: string;
  amount: number;
  count: number;
}

interface RevenueStats {
  totalRevenue: number;
  bookingCount: number;
}

const ClinicRevenue: React.FC = () => {
  const { clinicId } = useOutletContext<{ clinicId: string }>();
  const [stats, setStats] = useState<RevenueStats>({ totalRevenue: 0, bookingCount: 0 });
  const [doctorWise, setDoctorWise] = useState<DoctorRevenue[]>([]);
  const [_daily, setDaily] = useState<{ date: string; amount: number }[]>([]);
  const [monthly, setMonthly] = useState<{ month: string; amount: number }[]>([]);
  const [appointments, setAppointments] = useState<Appointment[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchRevenueData = async () => {
    setLoading(true);
    try {
      const token = localStorage.getItem("clinicToken");
      const res = await api.get(`/api/revenue/clinic/${clinicId}`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      if (res.data.success) {
        setStats(res.data.stats);
        setDoctorWise(res.data.doctorWiseRevenue);
        setDaily(res.data.dailyRevenue);
        setMonthly(res.data.monthlyRevenue);
        setAppointments(res.data.appointments);
      }
    } catch (err: any) {
      console.error(err);
      toast.error(err.response?.data?.message || "Failed to load revenue data");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (clinicId) {
      fetchRevenueData();
    }
  }, [clinicId]);

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[400px]">
        <div className="w-10 h-10 border-4 border-[#0c213e] border-t-transparent rounded-full animate-spin"></div>
        <p className="mt-3 text-sm text-gray-500 font-medium">Analyzing revenue records...</p>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-center bg-white p-6 rounded-2xl border border-gray-100 shadow-sm">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Clinic Revenue Panel</h1>
          <p className="text-sm text-gray-500">Track earnings, doctor billing performance, and transaction audits</p>
        </div>
        <button
          onClick={fetchRevenueData}
          className="flex items-center gap-2 px-4 py-2 border border-gray-200 hover:bg-gray-50 rounded-xl transition text-sm font-semibold text-gray-700"
        >
          <RefreshCw className="w-4 h-4" /> Refresh
        </button>
      </div>

      {/* Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="bg-gradient-to-br from-[#0c213e] to-[#163a6b] p-6 rounded-2xl text-white shadow-md relative overflow-hidden">
          <div className="absolute right-0 bottom-0 translate-x-4 translate-y-4 opacity-10">
            <IndianRupee className="w-48 h-48" />
          </div>
          <div className="flex items-center gap-3 mb-2">
            <div className="w-10 h-10 bg-white/10 rounded-xl flex items-center justify-center">
              <IndianRupee className="w-5 h-5 text-blue-200" />
            </div>
            <span className="text-sm font-medium text-blue-200 uppercase tracking-wide">Total Earnings</span>
          </div>
          <p className="text-3xl font-extrabold">₹{stats.totalRevenue.toLocaleString("en-IN")}</p>
          <p className="text-xs text-blue-200/80 mt-2">Cumulative revenue generated by clinic consultations</p>
        </div>

        <div className="bg-white p-6 rounded-2xl border border-gray-100 shadow-sm relative overflow-hidden">
          <div className="absolute right-0 bottom-0 translate-x-4 translate-y-4 opacity-5">
            <Users className="w-48 h-48 text-[#0c213e]" />
          </div>
          <div className="flex items-center gap-3 mb-2">
            <div className="w-10 h-10 bg-[#0c213e]/8 rounded-xl flex items-center justify-center">
              <Users className="w-5 h-5 text-[#0c213e]" />
            </div>
            <span className="text-sm font-medium text-gray-500 uppercase tracking-wide">Total Consultations</span>
          </div>
          <p className="text-3xl font-bold text-gray-900">{stats.bookingCount}</p>
          <p className="text-xs text-gray-400 mt-2">Total paid patient appointments completed</p>
        </div>
      </div>

      {/* Doctor wise breakdown and daily list */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Doctor contributions */}
        <div className="lg:col-span-2 bg-white p-6 rounded-2xl border border-gray-100 shadow-sm">
          <h2 className="text-lg font-bold text-gray-900 mb-4 flex items-center gap-2">
            <TrendingUp className="w-5 h-5 text-[#0c213e]" /> Doctor Earning Contribution
          </h2>
          {doctorWise.length === 0 ? (
            <p className="text-sm text-gray-500 italic">No doctors have booked patient earnings yet</p>
          ) : (
            <div className="space-y-4">
              {doctorWise.map((doc, idx) => {
                const percentage = stats.totalRevenue > 0 ? Math.round((doc.amount / stats.totalRevenue) * 100) : 0;
                return (
                  <div key={idx} className="space-y-2">
                    <div className="flex justify-between items-center text-sm font-medium text-gray-700">
                      <span>{doc.doctorName}</span>
                      <span className="text-gray-900 font-semibold">
                        ₹{doc.amount.toLocaleString("en-IN")} ({percentage}%)
                      </span>
                    </div>
                    <div className="w-full bg-gray-100 h-2.5 rounded-full overflow-hidden">
                      <div
                        className="bg-emerald-500 h-2.5 rounded-full"
                        style={{ width: `${percentage}%` }}
                      ></div>
                    </div>
                    <div className="text-xs text-gray-400">
                      {doc.count} Consultation{doc.count !== 1 ? "s" : ""} completed
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {/* Monthly summaries */}
        <div className="bg-white p-6 rounded-2xl border border-gray-100 shadow-sm">
          <h2 className="text-lg font-bold text-gray-900 mb-4 flex items-center gap-2">
            <Calendar className="w-5 h-5 text-[#0c213e]" /> Monthly Summary
          </h2>
          {monthly.length === 0 ? (
            <p className="text-sm text-gray-500 italic">No monthly summaries generated</p>
          ) : (
            <div className="divide-y divide-gray-100">
              {monthly.map((m, idx) => (
                <div key={idx} className="py-3 flex justify-between items-center">
                  <span className="text-sm font-medium text-gray-600">
                    {new Date(m.month + "-02").toLocaleDateString("en-IN", { month: "long", year: "numeric" })}
                  </span>
                  <span className="text-sm font-bold text-gray-900">
                    ₹{m.amount.toLocaleString("en-IN")}
                  </span>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Appointment revenue summary table */}
      <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
        <div className="px-6 py-5 border-b border-gray-100 flex items-center gap-2">
          <FileText className="w-5 h-5 text-[#0c213e]" />
          <h2 className="text-lg font-bold text-gray-900">Consultation Revenue History</h2>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm text-gray-700">
            <thead className="bg-gray-50/70 text-xs font-semibold text-gray-500 uppercase tracking-wider">
              <tr>
                <th className="px-6 py-4">Patient</th>
                <th className="px-6 py-4">Doctor</th>
                <th className="px-6 py-4">Date</th>
                <th className="px-6 py-4">Type</th>
                <th className="px-6 py-4">Amount</th>
                <th className="px-6 py-4">Status</th>
                <th className="px-6 py-4">Method</th>
                <th className="px-6 py-4">Transaction ID</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {appointments.length === 0 ? (
                <tr>
                  <td colSpan={8} className="px-6 py-10 text-center text-gray-400 italic">
                    No paid transactions found in this clinic
                  </td>
                </tr>
              ) : (
                appointments.map((appt) => (
                  <tr key={appt._id} className="hover:bg-gray-50/50 transition">
                    <td className="px-6 py-4 font-semibold text-gray-900">{appt.patientName}</td>
                    <td className="px-6 py-4">{appt.doctorName}</td>
                    <td className="px-6 py-4 text-xs font-medium text-gray-500">
                      {new Date(appt.date).toLocaleDateString("en-IN", {
                        day: "2-digit",
                        month: "short",
                        year: "numeric",
                        hour: "2-digit",
                        minute: "2-digit",
                      })}
                    </td>
                    <td className="px-6 py-4">
                      <span className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider ${
                        appt.type === "online"
                          ? "bg-blue-50 text-blue-700 border border-blue-100"
                          : "bg-indigo-50 text-indigo-700 border border-indigo-100"
                      }`}>
                        {appt.type}
                      </span>
                    </td>
                    <td className="px-6 py-4 font-bold text-gray-900">₹{appt.fees}</td>
                    <td className="px-6 py-4">
                      <span className="inline-flex items-center gap-1 bg-emerald-50 text-emerald-700 border border-emerald-100 px-2.5 py-0.5 rounded-full text-xs font-semibold">
                        <CheckCircle className="w-3 h-3 text-emerald-600" /> Paid
                      </span>
                    </td>
                    <td className="px-6 py-4 font-medium uppercase text-xs text-gray-600">{appt.paymentMethod}</td>
                    <td className="px-6 py-4 font-mono text-xs text-gray-400">{appt.transactionId}</td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default ClinicRevenue;
