import  { useState, useEffect } from "react";
import { useParams } from "react-router-dom";
import api from "../../Services/mainApi";
import { CheckBadgeIcon, ExclamationTriangleIcon, ArrowDownTrayIcon, ShareIcon } from "@heroicons/react/24/outline";
import { toast } from "react-toastify";

interface VerifiedReport {
  testName: string;
  patientName: string;
  labName: string;
  labCertificate: string;
  referredBy: string;
  dateGenerated: string;
  reportUrl: string;
  status: string;
}

export default function VerifyReport() {
  const { id } = useParams();
  const [report, setReport] = useState<VerifiedReport | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    const verifyReport = async () => {
      try {
        setLoading(true);
        // Note: this is a public API route, no token required
        const res = await api.get(`/api/lab/public/verify/${id}`);
        if (res.data.success) {
          setReport(res.data.report);
        }
      } catch (err: any) {
        setError(err.response?.data?.message || "Invalid or tampered QR Code. This report cannot be verified.");
      } finally {
        setLoading(false);
      }
    };

    verifyReport();
  }, [id]);

  if (loading) {
    return (
      <div className="min-h-screen bg-slate-50 flex flex-col items-center justify-center p-4">
        <div className="w-16 h-16 border-4 border-blue-500 border-t-transparent rounded-full animate-spin mb-4"></div>
        <p className="text-slate-600 font-medium animate-pulse">Verifying cryptographic signature...</p>
      </div>
    );
  }

  if (error || !report) {
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center p-4">
        <div className="max-w-md w-full bg-white rounded-3xl p-8 shadow-xl text-center border border-red-100">
          <div className="w-20 h-20 bg-red-100 text-red-500 rounded-full flex items-center justify-center mx-auto mb-6">
            <ExclamationTriangleIcon className="w-10 h-10" />
          </div>
          <h1 className="text-2xl font-bold text-slate-800 mb-2">Verification Failed</h1>
          <p className="text-slate-600 mb-8">{error}</p>
          <button onClick={() => window.location.href = '/'} className="px-6 py-3 bg-slate-800 text-white rounded-xl font-bold w-full hover:bg-slate-900 transition-all">
            Return to Home
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-2xl mx-auto">
        <div className="bg-white rounded-3xl shadow-xl overflow-hidden border border-emerald-100">
          
          <div className="bg-emerald-500 p-8 text-center text-white">
            <CheckBadgeIcon className="w-24 h-24 mx-auto text-emerald-100 mb-4" />
            <h1 className="text-3xl font-extrabold tracking-tight">Verified Genuine</h1>
            <p className="text-emerald-100 mt-2 font-medium">This report was electronically signed and verified.</p>
          </div>

          <div className="p-8">
            <div className="space-y-6">
              
              <div className="flex justify-between items-center pb-6 border-b border-slate-100">
                <div>
                  <p className="text-sm font-semibold text-slate-400 uppercase tracking-wider">Patient Name</p>
                  <p className="text-xl font-bold text-slate-800">{report.patientName}</p>
                </div>
                <div className="text-right">
                  <p className="text-sm font-semibold text-slate-400 uppercase tracking-wider">Test Performed</p>
                  <p className="text-lg font-bold text-blue-600">{report.testName}</p>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-6 pb-6 border-b border-slate-100">
                <div>
                  <p className="text-sm font-semibold text-slate-400 uppercase tracking-wider">Generated By</p>
                  <p className="text-md font-bold text-slate-800">{report.labName}</p>
                  {report.labCertificate && (
                    <p className="text-xs text-slate-500 font-medium">Cert: {report.labCertificate}</p>
                  )}
                </div>
                <div>
                  <p className="text-sm font-semibold text-slate-400 uppercase tracking-wider">Referred By</p>
                  <p className="text-md font-bold text-slate-800">Dr. {report.referredBy}</p>
                </div>
              </div>

              <div className="flex justify-between items-center pb-6 border-b border-slate-100">
                <div>
                  <p className="text-sm font-semibold text-slate-400 uppercase tracking-wider">Date of Issue</p>
                  <p className="text-md font-bold text-slate-800">{new Date(report.dateGenerated).toLocaleString()}</p>
                </div>
                <div>
                  <p className="text-sm font-semibold text-slate-400 uppercase tracking-wider">Status</p>
                  <span className="inline-flex items-center gap-1.5 px-3 py-1 bg-emerald-100 text-emerald-700 rounded-full text-xs font-bold mt-1">
                    <span className="w-1.5 h-1.5 bg-emerald-500 rounded-full animate-pulse"></span>
                    {report.status}
                  </span>
                </div>
              </div>

            </div>

            <div className="mt-8 flex gap-4">
              <a 
                href={report.reportUrl} 
                target="_blank" 
                rel="noreferrer"
                className="flex-1 flex justify-center items-center gap-2 px-6 py-4 bg-blue-600 text-white rounded-xl font-bold hover:bg-blue-700 transition-all shadow-lg shadow-blue-600/30"
              >
                <ArrowDownTrayIcon className="w-5 h-5" />
                Download Original PDF
              </a>
              <button 
                onClick={() => {
                  navigator.clipboard.writeText(window.location.href);
                  toast.success("Verification link copied to clipboard!");
                }}
                className="flex justify-center items-center gap-2 px-6 py-4 bg-slate-100 text-slate-700 rounded-xl font-bold hover:bg-slate-200 transition-all"
              >
                <ShareIcon className="w-5 h-5" />
              </button>
            </div>

          </div>
          
          <div className="bg-slate-50 p-4 text-center border-t border-slate-100">
            <p className="text-xs text-slate-400 font-medium">
              Powered by DoctorZ Enterprise EHR Blockchain-inspired Verification
            </p>
          </div>

        </div>
      </div>
    </div>
  );
}
